#include <iostream>
using namespace std;

int main() {
    try {
        // Bloque try interno
        try {
            throw 42; // Lanzar una excepci贸n de tipo int
        } catch (int value) {
            cout << "Excepci贸n parcialmente manejada: " << value << endl;
            throw; // Relanzar la excepci贸n capturada
        }
    } catch (int value) {
        cout << "Excepci贸n completamente manejada: " << value << endl;
    }
    return 0;
}
